### ISSUE TITLE
[BUG] Type 3 Projected Shield lists a Quick Action to Activate 

### ISSUE THREAD

**Issue by matscie** [Eranziel/foundryvtt-lancer#693] opened 2024-06-17 02:32 UTC
Type 3 Projected Sheild should be a Protocol to use, not a Quick Action

![image](https://github.com/Eranziel/foundryvtt-lancer/assets/58281831/57883991-fa95-4e8f-a55f-47fd49f75502)

**Comment by Eranziel** [comment] 2024-06-17 02:36
I believe this was caused by #657, which has since been fixed. Please try rebuilding your core data and then check the matching item in the compendium, and it should be fixed. You would need to replace the item on the mech actor after that.

**Comment by Eranziel** [comment] 2024-06-19 00:04
Confirming that this should be fixed on the latest version of Lancer (2.1.3) with updated core data.
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/49248157/b5c9497d-8b23-4d85-a525-ad2477781d34)

**Closed by Eranziel** 2024-06-19 00:04 UTC
Labels: bug, duplicate, question
