### ISSUE TITLE
[BUG] Targetting Hit/Miss display

### ISSUE THREAD

**Issue by theshipening** [Eranziel/foundryvtt-lancer#638] opened 2024-06-03 10:32 UTC
**Describe the bug**
In the chat display of the attack (roll, damage, ...), the display indicating whether you hit or missed the targeted opponent is missing

**To Reproduce**
Target enemy
Roll attack
Look at attack roll in chat

**Expected behavior**
A display in the attack roll indicating whether you hit or miss the opponent.

**Screenshots**
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/140340386/5b55024b-22d4-47e9-ac7c-b05484121453) lack of display (despite targetting)

**Platform (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Foundry version v11 315
 - Lancer system version 2.0.0

**Comment by Eranziel** [comment] 2024-06-03 17:39
This is proving to be a very tricky one to track down.
- I could not reproduce on a local installation of Foundry with 2.0 installed from the system install menu.
- I was able to reproduce initially on a Forge instance
- While debugging on Forge, the issue stopped presenting. I am now unable to reproduce on Forge.

The attack card output is behaving as though the attack automation setting is turned off.

**Comment by msprijatelj** [comment] 2024-06-03 18:42
I believe a workaround one user found was toggling the attack automation off and on again? Not sure yet if the automation will permanently stick after doing so.

**Comment by msprijatelj** [comment] 2024-06-04 01:11
This also occurs for weapons with the Heat (self) tag until toggling the Heat (Self) automation off and on again. Seems like this is some sort of issue with detecting the initial automation state post-migration.

**Comment by DirkMcThermot** [comment] 2024-06-07 13:39
Chiming in to add that the above workaround did in fact work for me AND it stuck through a restart of Foundry (for both the hit/miss automation and the self heat automation).

For context, my Foundry instance is hosted via Molten, a hosting service which does basically the same thing as Forge.

**Comment by Eranziel** [comment] 2024-06-09 05:10
Fixed by #675.

**Closed by Eranziel** 2024-06-09 05:10 UTC
Labels: bug, automation
