### ISSUE TITLE
[BUG] Lancer Initiative tracker does not show extra activations for Elites/Ultras

### ISSUE THREAD

**Issue by The-E** [Eranziel/foundryvtt-lancer#151] opened 2021-04-24 12:43 UTC
Similar to #150, the Lancer Initiative module does not work with 0.9; it can't access the number of activations an NPC with multiple activations has.

**To Reproduce**
1. Create an NPC with a template that grants extra activations
2. Start a combat turn
3. The NPC will have only one activation, despite multiples being tracked correctly on the character sheet

**Expected behavior**
The number of activations is tracked correctly in Lancer Initiative

**Screenshots**
![image](https://user-images.githubusercontent.com/280879/115959193-54270a00-a50b-11eb-8d24-47f6b324a1cc.png)

**Platform (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Foundry version 0.7.9
 - Lancer system version 0.9.0

**Discord contact info**
The_E#1047

**Comment by ScyllPoesis** [comment] 2021-04-24 14:13
Lancer Initiative is looking at (old path) `c.actor?.data.data?.activations` instead of (new path) `actor?.data.data?.derived.mmec.ent.Activations`.

Will update when we figure out whether to put the activation data back for compatibility or wait for the end of testing to get LI to update the path.

**Comment by BoltsJ** [comment] 2021-04-24 19:30
Can you file an issue on the Lancer Initiative repo so I can track this?

**Comment by Eranziel** [comment] 2021-04-25 18:07
v1.0 would be a good time to roll the Lancer Initiative functionality into the system proper. If we do so, should we add a check to make sure that the Lancer Initiative module is disabled?

**Comment by BoltsJ** [comment] 2021-04-26 16:34
As for adding it in, I was planning on sending a PR to do that sometime in the near future. I think there's a couple of small bugs, but I plan on releasing lancer-initiative on npm and adding it as a dependency.

**Comment by Alkyama** [comment] 2021-07-14 01:54
Tried reproducing the error with the latest Lancer Beta Release (0.9.5) and the latest Lancer Initiative, and it seems to be fixed. Elite and Ultra templates add extra activations as expected.

**Comment by BoltsJ** [comment] 2021-07-14 05:38
This was fixed in https://github.com/BoltsJ/lancer-initiative/issues/14

**Closed** 2021-08-30 04:17 UTC
Labels: bug, module
