### ISSUE TITLE
[FEATURE] Add interface element for ranking up Skills/Talents

### ISSUE THREAD

**Issue by stbz** [Eranziel/foundryvtt-lancer#51] opened 2020-07-23 19:25 UTC
Ranking up Talents and Skills is unintuitive.

Maybe we want to add a button or a field to control the level of a skill or talent.

**Comment by mason-bially** [comment] 2022-01-09 13:43
This seems to be relatively straight forward at the moment. Click `... -> edit -> + or -`. Would documentation in the wiki help close this issue?

**Comment by Eranziel** [comment] 2022-04-20 04:44
Duplicate of #181.

**Closed by Eranziel** 2022-04-20 04:44 UTC
Labels: feature, players
