### ISSUE TITLE
[FEATURE] Add a reference to item-id in Chat Messages generated from items

### ISSUE THREAD

**Issue by eclarke12** [Eranziel/foundryvtt-lancer#343] opened 2021-09-29 04:42 UTC
Currently it seems like items rolled to chat do not include the `item-id` in the html.

This means modules such as Maestro cannot infer that a chat message came from an item easily and find the relevant item (eg. in order to play an associated "Item Track" sound).

Generally other systems (eg. `dnd5e`) include a `data-item-id` attribute in the outer element of the chat message.

I am not overly familiar with the Lancer system so forgive me if I'm missing something

**Comment by mason-bially** [comment] 2022-01-14 00:24
I may have accidentally solved this during my work on #375 I guess I'll check to see if my branch fixes this and if there is any other improvements I can make related to this.

**Comment by eclarke12** [comment] 2022-01-14 14:57
> I may have accidentally solved this during my work on #375 I guess I'll check to see if my branch fixes this and if there is any other improvements I can make related to this.
> 
> @eclarke12 or anyone else, are there other example modules you can think of like this?

None that I'm aware of sorry.

**Comment by mason-bially** [comment] 2022-01-17 00:19
Well I can confirm that I have this working on my dev branch. Though before I forget, one will need to use `data-id` instead, since that's what the lancer system's internal helpers generate. This shouldn't be an issue for Maestro, even if the id it reads isn't strictly speaking an `item-id` all the time.
![image](https://user-images.githubusercontent.com/1072924/149684044-7f9ad321-37ee-4a40-b1b8-579b0ee59605.png)

**Comment by mason-bially** [comment] 2022-04-21 21:09
Given the current caveat above this has been fixed as of #375. I have pending documentation for Maestro to be put on the wiki (but I need access).

**Closed** 2022-04-21 21:51 UTC
Labels: feature, good first issue, macros
