### ISSUE TITLE
[BUG] Changing Comp/Con code for Actor and triggering sync doesn't work

### ISSUE THREAD

**Issue by flukowski** [Eranziel/foundryvtt-lancer#128] opened 2020-12-25 05:54 UTC
**Describe the bug**
Changing Comp/Con code for Actor and triggering sync doesn't work

**To Reproduce**
1. Create new Actor and sync with comp/con code
2. Change comp/con code to a different character and sync
3. Actor doesn't change

**Expected behavior**
New character should replace existing character in Actor

**Platform (please complete the following information):**
 - OS: [e.g. Windows] Node on AWS
 - Browser [e.g. chrome, firefox] Chrome
 - Foundry version [e.g. 0.6.6] 0.7.9
 - Lancer system version [e.g. 0.1.10] 0.1.19

**Discord contact info**
If you are willing to answer questions regarding this bug report on Discord, or if you want to be notified when it is fixed, please leave your Discord ID here.
Fluke#0640

**Comment by flukowski** [comment] 2020-12-29 06:03
I'll look into fixing this one myself.

**Comment by Eranziel** [comment] 2021-01-21 02:57
I'm not able to reproduce on 0.1.19. Are you sure you're actually performing a sync? There is a bit of a UI bug where clicking out of the text box consumes the click event, so you need to click out and then click update.

**Comment by Grygon** [comment] 2021-04-23 14:55
Definitely related to #48, but this in particular is something we should look at resolving for v1.0

**Comment by Grygon** [comment] 2021-05-31 07:01
Also tied into #168, will work on a better loading interface to handle both in a way that's more intuitive for consuming clicks

**Comment by Grygon** [comment] 2021-08-11 03:08
Fixed in 0.9.6

**Closed by Grygon** 2021-08-11 03:08 UTC
Labels: bug, players, C/C, fixed, sheet
