### ISSUE TITLE
[BUG] Legendry Trtait automation is display incorrectly when two 1s are rolled.

### ISSUE THREAD

**Issue by Trackwolf43** [Eranziel/foundryvtt-lancer#754] opened 2024-08-21 00:10 UTC
**Describe the bug**
When a Veteran template on an NPC is place, they get the legendary optional automatically rolled twice and picking the highest d6. But if two 1s are rolled, the system will assume it was a crushing it on the structure table and assuming the mech is destroyed.

**To Reproduce**
1. Have an NPC with the veteran template, and the Legendary optional trait.
2. Have it take structure damage as many times as until it rolls two 1s (assuming it is the first structure it lost each time).

**Expected behavior**
To have the normal structure damage be display.

**Screenshots**

![Screenshot 2024-08-20 190621](https://github.com/user-attachments/assets/8c8e4b19-c452-4f9a-a1fa-d5ce17596931)

**Platform (please complete the following information):**
 - Foundry version [v11 315]
 - Lancer system version [2.2.4]

**Discord contact info**
Trackwolf#4115

**Comment by Eranziel** [comment] 2024-09-29 15:45
Duplicate of #768.

**Closed** 2024-09-29 15:46 UTC
Labels: bug, automation
