### ISSUE TITLE
[BUG] Deleting an item from player inventory that is currently equipped does not remove the equipped item and causes errors when attempting to sync from Comp/Con

### ISSUE THREAD

**Issue by Z3nner** [Eranziel/foundryvtt-lancer#269] opened 2021-08-06 18:47 UTC
**Describe the bug**
If an item is deleted from a player inventory before unequipping it the item will remain equipped.  However, from this point forward syncing a character will trigger an lcp related error

**To Reproduce**
1. Drag a weapon from compendium to a player's weapon mount
2. Delete this weapon from the player inventory
3. OPTIONAL: delete the weapon from the player weapon mount
4. Attempt to Sync from Comp/Con

**Expected behavior**
Removing a weapon from an inventory would ideally remove it if also currently equipped.

**Platform (please complete the following information):**
 Foundry 0.8.8
Lancer 0.9.5

**Additional context**
Discovered this while attempting to troubleshoot weapon mod usability for another GM.

**Discord contact info**
Zenn#4226
e.g. Eranziel#1234

**Comment by whitespine** [comment] 2021-08-06 23:47
Unable to reproduce locally. Possibly just fixed on newer builds, but I'm not confident on that.

If you contact me on discord (also WHITESPINE) I could maybe hop into a temporary GM user on your server, watch it happen in-vivo?

**Comment by Eranziel** [comment] 2022-01-16 06:23
Can't duplicate on dev, closing. Please let us know if you are still having this happen and we'll re-open.

**Closed by Eranziel** 2022-01-16 06:23 UTC
Labels: bug, question, C/C
