### ISSUE TITLE
[BUG] Chomolungma's Invade Options Don't Output To Chat

### ISSUE THREAD

**Issue by nomiddlename303** [Eranziel/foundryvtt-lancer#525] opened 2023-02-20 02:52 UTC
**Describe the bug**
The Chomolungma has a core passive that gives it two invade options - these show up just fine on the sheet (see below), but when I click the black 'Invade' button it throws an error instead of outputting to chat.

**To Reproduce**
1. Go to a mech sheet with the GMS Chomolungma
2. Click the black 'Invade' button under Balance Control Lockout or System Crusher
3. See error below

**Expected behavior**
A tech attack popup appears, and is rolled and outputted to chat like other invade systems.

**Screenshots**
![image](https://user-images.githubusercontent.com/96335543/219998270-1c50ca2a-5e37-4641-8e69-04acad43725a.png)
![image](https://user-images.githubusercontent.com/96335543/219998354-af252ded-848a-4bfd-8312-fe6c6180c973.png)

**Platform (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome Version 110.0.5481.104
 - Foundry Version: Version 10 Build 291
 - Lancer System Version: 1.5.1

**Additional context**
This bug persists with no active modules.

**Discord contact info**
Nope#9465

**Comment by msprijatelj** [comment] 2023-02-20 14:48
Looks like a duplicate of #498 ?

**Comment by Eranziel** [comment] 2023-07-26 22:56
Yup, duplicate.

**Closed by Eranziel** 2023-07-26 22:56 UTC
Labels: bug, triage
