### ISSUE TITLE
[BUG] Structure Macro does not work

### ISSUE THREAD

**Issue by DMRaven** [Eranziel/foundryvtt-lancer#267] opened 2021-08-02 01:05 UTC
**Describe the bug**
This is two similar but possibly different issues. When using the Structure Macro on a PC mech, no die roll is made in the chat window. Structure is reduced by 1 and hit points are returned to full. Negative HP are no longer considered.

When using the structure macro on a NPC mech, an alert saying "Currently just doing normal mech structure" pops up instead.

**To Reproduce**
1. Go to Structure Token Macro in Lancer v.9.5
2. Click on the Structure Token macro in the macro toolbar.
3. Observe the lack of die roll or alert across the upper middle portion of the screen.

**Expected behavior**
When the Structure Token macro is clicked, a number of d6's equal to lost structure should be rolled on the structure damage table. This should work for both NPCs with multiple structure and PC mechs.

**Screenshots**

**Platform (please complete the following information):**
 - OS: [e.g. Windows] Windows 10
 - Browser [e.g. chrome, firefox] Foundry VTT Application
 - Foundry version [e.g. 0.6.6] 0.8.8
 - Lancer system version [e.g. 0.1.10] 0.9.5

**Additional context**

**Discord contact info**
If you are willing to answer questions regarding this bug report on Discord, or if you want to be notified when it is fixed, please leave your Discord ID here.
Demi_Dad#4073

**Comment by SohumB** [comment] 2021-08-06 04:54
Duplicate of #261. Sorry! We have a fix in the works.

**Closed** 2021-08-06 04:55 UTC
Labels: bug, duplicate, triage, fixed

**Comment by DMRaven** [comment] 2021-08-10 12:51
Hello, is there a projected release date of the version that has this fix? Also thank you for all your work!

**Comment by SohumB** [comment] 2021-08-11 03:19
Right now! 🥳
