### ISSUE TITLE
[BUG] Doesn't allow download and doesn't show up on the system install

### ISSUE THREAD

**Issue by TheBot28** [Eranziel/foundryvtt-lancer#689] opened 2024-06-16 07:49 UTC
The Bug
I have both tried downloading of the foundry in the app and tried inputting the git hub https but it always gives this:
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/91368742/c577d46e-a200-4f70-95bb-2feec3f83d52)
If it matters I am currently running the version 12 stable - build 327

First time using foundry and im trying to set up a lancer campaign but when I try to find the system it doesn't show up and when I try to download it via the git hub https it always gives that error.

**Comment by Eranziel** [comment] 2024-06-16 14:34
Lancer is not yet compatible with v12. You will need to use Foundry v11, and then Lancer will appear in the system browser.

**Comment by Eranziel** [comment] 2024-06-16 14:35
Closing as duplicate of #650.

**Closed** 2024-06-16 14:35 UTC
Labels: duplicate
