### ISSUE TITLE
[BUG] Weapon Effects Do Not Import

### ISSUE THREAD

**Issue by HeyoBeo** [Eranziel/foundryvtt-lancer#686] opened 2024-06-14 01:34 UTC
**Describe the bug**
NPC weapons seem to be missing text related to On Attack, On Hit, and On Crit effects.

**To Reproduce**
1. Import an LCP that contains NPC data into the Compendium.
2. Navigate to the NPC Items folder, then select an NPC Class or Template with important weapon effects.
3. These weapons will be missing the aforementioned text.

**Expected behavior**
On Hit and On Crit effects should be placed in the correct boxes so that GMs can more easily understand what kind of character they're building and players can better understand how certain attacks behave.

**Screenshots**
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/172698397/013d0ed1-30e3-437b-9104-fcfedbe49c89)
![image](https://github.com/Eranziel/foundryvtt-lancer/assets/172698397/b26faf80-085a-48d9-91ea-d8c8167170bd)

**Platform (please complete the following information):**
 - OS: Windows
 - Platform: Foundry VTT program for Windows
 - v11, build 315
 - Lancer system version 2.1.0

**Additional context**

**Discord contact info**
Display Name: HeyoBeo
User Name: beohel

**Comment by Eranziel** [comment] 2024-06-14 01:58
Duplicate of #676.

**Closed** 2024-06-14 01:59 UTC
Labels: duplicate

**Comment by Eranziel** [comment] 2024-06-14 04:58
Good news, though! It will be fixed in the next release.
