### ISSUE TITLE
[BUG] Most system effects missing

### ISSUE THREAD

**Issue by perijove** [Eranziel/foundryvtt-lancer#58] opened 2020-08-09 05:17 UTC
**Describe the bug**
System effects appear to be missing in the compendium.

**To Reproduce**
1. Create a new "pilot" actor
2. Open the Systems compendium pack
3. Click on a system to open the description, or drag it onto a pilot actor to equip it to the character
4. Check to see if the Effects field is populated

**Expected behavior**
I would expect the system effects to be part of the compendium. Some are there - the Autoloader Drone has the full text, and the ASURA-class NHP has part of its text.

**Screenshots**
![Compendium missing](https://user-images.githubusercontent.com/58275662/89725445-a8ba4180-d9dd-11ea-883f-887afedaf844.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - LANCER System Version  0.1.2
 - Foundry Version 0.6.5

**Additional context**
The console did not produce any errors when I opened the system and applied it to an actor.
I checked as player and gamemaster, and saw the same behavior.

**Comment by Eranziel** [comment] 2020-08-10 13:12
Duplicate of #22.

**Closed by Eranziel** 2020-08-10 13:12 UTC
Labels: duplicate
