### ISSUE TITLE
[BUG] Pilot overshield field is named differently than other actor types.

### ISSUE THREAD

**Issue by BoltsJ** [Eranziel/foundryvtt-lancer#272] opened 2021-08-08 19:39 UTC
**Describe the bug**
Pilot actors store overshield in `data.current_overshield` but all other actor types store overshield in `data.overshield`

**To Reproduce**
1. Create a pilot and a mech
2. access `pilot.data.data.overshield` leads to `undefined`
3. access `mech.data.data.overshield` leads to `0`
4. access `pilot.data.data.current_overshield` leads to `0`
5. access `mech.data.data.current_overshield` leads to `undefined`

**Expected behavior**
All actors should have the same parameter for overshield.

**Screenshots**
Pilot: 
![image](https://user-images.githubusercontent.com/182554/128643725-45f649b7-c0ef-4054-baf5-c243863a9db1.png)

Mech:
![image](https://user-images.githubusercontent.com/182554/128643734-a514f957-ab6c-4f08-a4f2-2ebc82552a1b.png)

**Platform (please complete the following information):**
 - OS: Any
 - Browser: Any
 - Foundry version: 0.8.8
 - Lancer system version: 0.9.5

**Additional context**

**Discord contact info**
Bolts#9418

**Comment by whitespine** [comment] 2021-08-28 20:15
Closing this as work-wise it is an effective duplicate of #271 . Should be easy fix from here

**Closed by whitespine** 2021-08-28 20:15 UTC
Labels: bug, triage
