### ISSUE TITLE
[BUG] Flex Mount displays one aux weapon upon importing

### ISSUE THREAD

**Issue by TonySandwich** [Eranziel/foundryvtt-lancer#711] opened 2024-06-27 16:50 UTC
When importing a mech loadout with 2 aux weapons in a Flex Mount, Foundry will display only 1 Aux weapon in the Flex Mount.

Example : A Tokugawa with 2 Shock Knifes on its flex mount on COMp/CON. When importing on Foundry with the .json file, only 1 Shock Knife is available for Skirmish.

Screenshots : 
https://cdn.discordapp.com/attachments/760966283545673730/1255920335056932924/image.png?ex=667ee275&is=667d90f5&hm=d9943e53bdf021cbeeb1cd0762500328a8f2da81ba522dd953b0d2127a32f93f&
https://cdn.discordapp.com/attachments/760966283545673730/1255920404304756796/image.png?ex=667ee286&is=667d9106&hm=1fb848b33aab1d0fb32ff07954b3bb83fcab7958221e8747e524eaf922ac15c6&

**Platform (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Foundry version 11.315
 - Lancer system version 2.1.4

**Discord contact info**
tonysan on Discord

**Comment by Eranziel** [comment] 2024-06-28 19:23
Duplicate of #712.

**Closed by Eranziel** 2024-06-28 19:23 UTC
Labels: bug, duplicate
