### ISSUE TITLE
[BUG] If you put the supermassive mod on a Hammer U-RPL, you get knockback 31

### ISSUE THREAD

**Issue by Polish-vamp** [Eranziel/foundryvtt-lancer#480] opened 2022-10-07 18:28 UTC
One of my players misunderstood how mods worked, and added these two together. While this combination isn't legal, whatever caused this could also cause other problems, however I haven't been able to replicate this with any other combination. I think foundry is adding the knockback as strings instead of actual numbers.

<img width="81" alt="image" src="https://user-images.githubusercontent.com/103609046/194625029-c644fb5d-a404-4512-a846-dcafd9a02745.png">

If you need to contact me on discord for anything, I am The Polish Vampire#4644

**Comment by Eranziel** [comment] 2023-02-12 03:58
I believe this was due to an old version of the Long Rim LCP. Can't reproduce, closing.

**Closed by Eranziel** 2023-02-12 03:58 UTC
Labels: bug, triage
